CREATE OR REPLACE VIEW COSTLY_DISEASE_VIEW AS
SELECT 
    f.YEAR,
    f.BENEFICIARY_ID,
    f.PAYMENT_INPATIENT,
    f.PAYMENT_OUTPATIENT,
    f.PAYMENT_CARRIER,
    (f.PAYMENT_INPATIENT + f.PAYMENT_OUTPATIENT + f.PAYMENT_CARRIER) AS TOTAL_ANNUAL_PAYMENT,
    d.CANCER,
    d.COPD,
    d.DEPRESSION,
    d.CHRONIC_KIDNEY_DISEASE, 
    d.ALZHEIMERS_DISEASE,
    d.CONGESTIVE_HEART_FAILURE,
    d.DIABETES,
    d.ISCHEMIC_HEART_DISEASE,
    d.OSTEOPOROSIS,
    d.RHEUMATOID_ARTHRITIS_OA,
    d.STROKE    
FROM FINANCIALS f , 
	 DISEASES d
WHERE f.BENEFICIARY_ID = d.BENEFICIARY_ID 
 AND   f.YEAR = d.YEAR;