CREATE OR REPLACE VIEW MEDICARE_DATA AS
SELECT 
    b.BENEFICIARY_ID,
    b.GENDER_CODE,
    b.RACE_CODE,
    b.BIRTH_DATE,
    b.DEATH_DATE,
    d.YEAR,
    d.ALZHEIMERS_DISEASE, 
    d.CONGESTIVE_HEART_FAILURE, 
    d.CHRONIC_KIDNEY_DISEASE, 
    d.CANCER, 
    d.COPD, 
    d.DEPRESSION,
    d.DIABETES,
    d.ISCHEMIC_HEART_DISEASE, 
    d.OSTEOPOROSIS,
    d.RHEUMATOID_ARTHRITIS_OA,
    d.STROKE,
    c.ESRD_INDICATOR,
    c.STATE_CODE,
    c.COUNTY_CODE,
    c.MEDICARE_COVERAGE_MONTHS,
    c.SUPPLEMENTARY_COVERAGE_MONTHS,
    c.HMO_COVERAGE_MONTHS,
    c.PLAN_COVERAGE_MONTHS,
    (f.MEDICAL_REIMBURSEMENT_INPATIENT + f.MEDICAL_REIMBURSEMENT_OUTPATIENT + f.MEDICAL_REIMBURSEMENT_CARRIER) AS TOTAL_REIMBURSEMENT,
    (f.BENEFICIARY_RESPONSIBILITY_INPATIENT + f.BENEFICIARY_RESPONSIBILITY_OUTPATIENT + f.BENEFICIARY_RESPONSIBILITY_CARRIER) AS TOTAL_RESPONSIBILITY,
    (f.PAYMENT_INPATIENT + f.PAYMENT_OUTPATIENT + f.PAYMENT_CARRIER) AS TOTAL_PAYMENT
FROM BENEFICIARIES b,
     DISEASES d,
     FINANCIALS f,
     COVERAGE c
WHERE b.BENEFICIARY_ID = d.BENEFICIARY_ID
AND   d.BENEFICIARY_ID = f.BENEFICIARY_ID
AND   f.BENEFICIARY_ID = c.BENEFICIARY_ID
AND   d.YEAR = f.YEAR
AND   d.YEAR = c.YEAR;