CREATE OR REPLACE VIEW MORTALITY_VIEW AS
SELECT 
    d.YEAR,
    b.GENDER_CODE,
    CASE WHEN b.DEATH_DATE IS NOT NULL AND b.DEATH_DATE != '' THEN 1 ELSE 0 END AS IS_DECEASED,
    d.ALZHEIMERS_DISEASE, 
    d.CONGESTIVE_HEART_FAILURE,
    d.CHRONIC_KIDNEY_DISEASE, 
    d.CANCER,
    d.COPD,
    d.DEPRESSION,
    d.DIABETES,
    d.ISCHEMIC_HEART_DISEASE,
    d.OSTEOPOROSIS,
    d.RHEUMATOID_ARTHRITIS_OA,
    d.STROKE,
    (d.YEAR - LEFT(b.BIRTH_DATE, 4)) AS AGE_AT_YEAR
FROM BENEFICIARIES b,
	 DISEASES d
WHERE b.BENEFICIARY_ID = d.BENEFICIARY_ID;