CREATE OR REPLACE VIEW MULTIMORBIDITY_VIEW AS
SELECT 
    d.BENEFICIARY_ID,
    d.YEAR,
    (d.ALZHEIMERS_DISEASE +
     d.CONGESTIVE_HEART_FAILURE + 
	 d.CHRONIC_KIDNEY_DISEASE + 
     d.CANCER + 
     d.COPD + 
     d.DEPRESSION + 
     d.DIABETES + 
     d.ISCHEMIC_HEART_DISEASE + 
     d.OSTEOPOROSIS + 
     d.RHEUMATOID_ARTHRITIS_OA +
     d.STROKE) AS DISEASE_COUNT,
    (f.PAYMENT_INPATIENT + f.PAYMENT_OUTPATIENT + f.PAYMENT_CARRIER) AS TOTAL_COST
FROM DISEASES d , 
	 FINANCIALS f
WHERE d.BENEFICIARY_ID = f.BENEFICIARY_ID 
 AND d.YEAR = f.YEAR;