SELECT 
    FLOOR(mo.AGE_AT_YEAR/10)*10 AS AGE_GROUP,
    m.DISEASE_COUNT,
    COUNT(*) AS PATIENTS,
    ROUND(AVG(m.TOTAL_COST),2) AS AVG_COST,
    ROUND(MAX(m.TOTAL_COST),2) AS MAX_COST
FROM MULTIMORBIDITY_VIEW m, MORTALITY_VIEW mo
WHERE m.BENEFICIARY_ID = mo.BENEFICIARY_ID
       AND m.YEAR = mo.YEAR
GROUP BY AGE_GROUP, m.DISEASE_COUNT
ORDER BY AVG_COST DESC;