SELECT 
    YEAR,
    CASE
        WHEN DISEASE_COUNT = 0 THEN 'Healthy'
        WHEN DISEASE_COUNT BETWEEN 1 AND 2 THEN 'Moderate Risk'
        WHEN DISEASE_COUNT BETWEEN 3 AND 4 THEN 'High Risk'
        ELSE 'Very High Risk'
    END AS RISK_GROUP,
    COUNT(*) AS PATIENTS,
    ROUND(AVG(TOTAL_COST),2) AS AVG_COST,
    ROUND(MAX(TOTAL_COST),2) AS MAX_COST
FROM MULTIMORBIDITY_VIEW
GROUP BY 
    YEAR,
    RISK_GROUP
ORDER BY 
    YEAR,
    AVG_COST DESC;