SELECT 
    mo.YEAR,
    FLOOR(mo.AGE_AT_YEAR/10)*10 AS AGE_GROUP,
    m.DISEASE_COUNT,
    COUNT(*) AS PATIENTS,
    ROUND(AVG(m.TOTAL_COST),2) AS AVG_COST
FROM MORTALITY_VIEW mo, MULTIMORBIDITY_VIEW m
WHERE mo.BENEFICIARY_ID = m.BENEFICIARY_ID 
       AND mo.YEAR = m.YEAR
GROUP BY 
    mo.YEAR,
    AGE_GROUP,
    m.DISEASE_COUNT
ORDER BY 
    AGE_GROUP,
    m.DISEASE_COUNT;