SELECT 
    m.YEAR,
    CASE 
        WHEN mo.AGE_AT_YEAR < 50 THEN 'Under 50'
        WHEN mo.AGE_AT_YEAR BETWEEN 50 AND 64 THEN '50-64'
        WHEN mo.AGE_AT_YEAR BETWEEN 65 AND 74 THEN '65-74'
        WHEN mo.AGE_AT_YEAR BETWEEN 75 AND 84 THEN '75-84'
        ELSE '85+'
    END AS AGE_GROUP,
    m.DISEASE_COUNT,
    COUNT(*) AS TOTAL_PATIENTS,
    ROUND(AVG(m.TOTAL_COST),2) AS AVG_COST,
    ROUND(MAX(m.TOTAL_COST),2) AS MAX_COST,
    SUM(mo.IS_DECEASED) AS TOTAL_DEATHS,
    ROUND(SUM(mo.IS_DECEASED)/COUNT(*)*100,2) AS MORTALITY_RATE
FROM MULTIMORBIDITY_VIEW m , MORTALITY_VIEW mo
WHERE m.BENEFICIARY_ID = mo.BENEFICIARY_ID 
      AND m.YEAR = mo.YEAR
GROUP BY 
    m.YEAR,
    AGE_GROUP,
    m.DISEASE_COUNT
ORDER BY 
    m.YEAR,
    AGE_GROUP,
    m.DISEASE_COUNT;