SELECT 
    YEAR,
    SUM(DIABETES) AS DIABETES_CASES,
    SUM(COPD) AS COPD_CASES,
    SUM(CANCER) AS CANCER_CASES,
    SUM(STROKE) AS STROKE_CASES,
    COUNT(*) AS TOTAL_PATIENTS,
    ROUND(AVG(TOTAL_ANNUAL_PAYMENT),2) AS AVG_COST
FROM COSTLY_DISEASE_VIEW
GROUP BY YEAR
ORDER BY AVG_COST DESC;