SELECT 
    YEAR,
    COUNT(*) AS PATIENTS,
    SUM(DIABETES) AS DIABETES_CASES,
    SUM(COPD) AS COPD_CASES,
    SUM(CANCER) AS CANCER_CASES,
    SUM(CHRONIC_KIDNEY_DISEASE) AS CKD_CASES,
    SUM(CONGESTIVE_HEART_FAILURE) AS CHF_CASES,
    ROUND(AVG(TOTAL_ANNUAL_PAYMENT),2) AS AVG_COST,
    ROUND(MAX(TOTAL_ANNUAL_PAYMENT),2) AS MAX_COST
FROM COSTLY_DISEASE_VIEW
GROUP BY YEAR
ORDER BY AVG_COST DESC;