CREATE TABLE BENEFICIARIES (
    BENEFICIARY_ID VARCHAR(50),
    BIRTH_DATE     INT,
    DEATH_DATE     VARCHAR(9),
    GENDER_CODE    INT,
    RACE_CODE      INT,
    CONSTRAINT BENEFICIARYID_PK 		   PRIMARY KEY (BENEFICIARY_ID)
    CONSTRAINT BENEFICIARIES_RACECODE_FK   FOREIGN KEY (RACE_CODE) REFERENCES RACES(RACE_CODE) ON DELETE CASCADE
);


