CREATE TABLE COUNTIES (
    COUNTY_CODE INT,
    COUNTY_NAME VARCHAR(100) NOT NULL,
    STATE_CODE  VARCHAR(2)   NOT NULL,
    CONSTRAINT COUNTYCODE_PK PRIMARY KEY (COUNTY_CODE,STATE_CODE),
    CONSTRAINT COUNTIES_STATECODE_FK FOREIGN KEY (STATE_CODE) REFERENCES STATES (STATE_CODE) ON DELETE CASCADE
);

