CREATE TABLE COVERAGE (
    BENEFICIARY_ID 					VARCHAR(50),
    YEAR 							INT,
    ESRD_INDICATOR 					INT,
    STATE_CODE 						VARCHAR(2),
    COUNTY_CODE 					INT,
    MEDICARE_COVERAGE_MONTHS 		INT,
    SUPPLEMENTARY_COVERAGE_MONTHS 	INT,
    HMO_COVERAGE_MONTHS 			INT,
    PLAN_COVERAGE_MONTHS 			VARCHAR(50),
    CONSTRAINT COVERAGE_BENEFICIARYEAR_PK  PRIMARY KEY (BENEFICIARY_ID, YEAR),
    CONSTRAINT COVERAGE_BENEFICIARY_FK     FOREIGN KEY (BENEFICIARY_ID) REFERENCES BENEFICIARIES(BENEFICIARY_ID)
);
