CREATE TABLE COVERAGE (
    BENEFICIARY_ID 					VARCHAR(50),
    YEAR 							INT,
    ESRD_INDICATOR 					INT,
    STATE_CODE 						VARCHAR(2),
    COUNTY_CODE 					INT,
    MEDICARE_COVERAGE_MONTHS 		INT,
    SUPPLEMENTARY_COVERAGE_MONTHS 	INT,
    HMO_COVERAGE_MONTHS 			INT,
    PLAN_COVERAGE_MONTHS 			VARCHAR(50),
    CONSTRAINT COVERAGE_BENEFICIARYEAR_PK  PRIMARY KEY (BENEFICIARY_ID, YEAR),
    CONSTRAINT COVERAGE_BENEFICIARY_FK     FOREIGN KEY (BENEFICIARY_ID)         REFERENCES BENEFICIARIES(BENEFICIARY_ID) ON DELETE CASCADE
);
COMMENT ON COLUMN COVERAGE.SUPPLEMENTARY_COVERAGE_MONTHS  IS 'Number of months in the year the beneficiary had Medicare Part B supplementary coverage (0-12)';
COMMENT ON COLUMN COVERAGE.HMO_COVERAGE_MONTHS  IS 'Number of months the beneficiary was enrolled in a Medicare Advantage / HMO plan during the year (0-12)';
COMMENT ON COLUMN COVERAGE.PLAN_COVERAGE_MONTHS  IS 'Number of months the beneficiary had Medicare Part D prescription drug plan coverage (0-12)';

