CREATE TABLE DISEASES (
    BENEFICIARY_ID 			 VARCHAR(50),
    YEAR 					 INT,
    ALZHEIMERS_DISEASE 		 		 INT,
    CONGESTIVE_HEART_FAILURE 			 INT,
    CHRONIC_KIDNEY_DISEASE   			 INT,
    CANCER 					 INT,
    COPD 					 INT,
    DEPRESSN 					 INT,
    DIABETES 					 INT,
    ISCHEMIC_HEART_DISEASE 	 		 INT,
    OSTEOPOROSIS 			 	 INT,
    RHEUMATOID_ARTHRITIS_OA  			 INT,
    STROKE 					 INT,
    CONSTRAINT DISEASES_PK 	PRIMARY KEY (BENEFICIARY_ID, YEAR),
    CONSTRAINT DISEASES_BENEFICIARY_FK FOREIGN KEY (BENEFICIARY_ID) REFERENCES BENEFICIARIES (BENEFICIARY_ID)
);


