CREATE TABLE FINANCIALS (
    BENEFICIARY_ID 						  VARCHAR(50),
    YEAR 								  INT,
    MEDICAL_REIMBURSEMENT_INPATIENT 	  DOUBLE,
    beneficiary_responsibility_inpatient  DOUBLE,
    PAYMENT_INPATIENT 					  DOUBLE,
    MEDICAL_REIMBURSEMENT_OUTPATIENT 	  DOUBLE,
    beneficiary_responsibility_outpatient DOUBLE,
    PAYMENT_OUTPATIENT 					  DOUBLE,
    MEDICAL_REIMBURSEMENT_CARRIER 	      DOUBLE,
    beneficiary_responsibility_carrier 	  DOUBLE,
    PAYMENT_CARRIER 					  DOUBLE,
    PRIMARY KEY (BENEFICIARY_ID, YEAR), 
    CONSTRAINT FINANCIALS_BENEFICIARY_FK FOREIGN KEY (BENEFICIARY_ID) REFERENCES BENEFICIARIES(BENEFICIARY_ID)
);




