CREATE TABLE TEMP_STAGING (beneficiary_id varchar(50) 
						  ,birth_date int 
						  ,death_date varchar(9) 
						  ,gender_code int 
						  ,race_code int 
						  ,esrd_indicator int 
						  ,state_code varchar(2) 
						  ,county_code int 
						  ,medicare_coverage_months int 
						  ,supplementary_coverage_months int 
						  ,hmo_coverage_months int 
						  ,plan_coverage_months text 
						  ,alzheimers_disease int 
						  ,congestive_heart_failure int 
						  ,chronic_kidney_disease int 
						  ,cancer int 
						  ,copd int 
						  ,depression int 
						  ,diabetes int 
						  ,ischemic_heart_disease int 
						  ,osteoporosis int 
						  ,rheumatoid_arthritis_oa int 
						  ,stroke int 
						  ,medical_reimbursement_inpatient double 
						  ,beneficiary_responsibility_inpatient double 
						  ,payment_inpatient double 
						  ,medical_reimbursement_outpatient double 
						  ,beneficiary_responsibility_outpatient double 
						  ,payment_outpatient double 
						  ,medical_reimbursement_carrier double 
						  ,beneficiary_responsibility_carrier double 
						  ,payment_carrier double
						  );