DELIMITER $$

CREATE PROCEDURE MEDICARE_ANALYSIS(IN target_year INT)
BEGIN

-- Average cost per year

SELECT 
    YEAR,
    COUNT(*) AS TOTAL_PATIENTS,
    ROUND(AVG(TOTAL_PAYMENT),2) AS AVG_COST,
    ROUND(SUM(TOTAL_PAYMENT),2) AS TOTAL_COST
FROM MEDICARE_DATA
WHERE YEAR = target_year
GROUP BY YEAR
ORDER BY YEAR;


-- Disease prevalence

SELECT 
    YEAR,
    SUM(CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) AS DIABETES_CASES,
    SUM(CASE WHEN COPD = 1 THEN 1 ELSE 0 END) AS COPD_CASES,
    SUM(CASE WHEN CANCER = 1 THEN 1 ELSE 0 END) AS CANCER_CASES,
    SUM(CASE WHEN STROKE = 1 THEN 1 ELSE 0 END) AS STROKE_CASES
FROM MEDICARE_DATA
WHERE YEAR = target_year
GROUP BY YEAR;


-- Cost by gender

SELECT 
    GENDER_CODE,
    COUNT(*) AS PATIENTS,
    ROUND(AVG(TOTAL_PAYMENT),2) AS AVG_COST,
    ROUND(MAX(TOTAL_PAYMENT),2) AS MAX_COST
FROM MEDICARE_DATA
WHERE YEAR = target_year
GROUP BY GENDER_CODE;


-- Cost by state

SELECT 
    STATE_CODE,
    COUNT(*) AS PATIENTS,
    ROUND(AVG(TOTAL_PAYMENT),2) AS AVG_COST
FROM MEDICARE_DATA
WHERE YEAR = target_year
GROUP BY STATE_CODE
ORDER BY AVG_COST DESC;


-- Multimorbidity cost escalation

SELECT 
    (
      (CASE WHEN DIABETES = 1 THEN 1 ELSE 0 END) +
      (CASE WHEN COPD = 1 THEN 1 ELSE 0 END) +
      (CASE WHEN CANCER = 1 THEN 1 ELSE 0 END) +
      (CASE WHEN STROKE = 1 THEN 1 ELSE 0 END)
    ) AS DISEASE_COUNT,
    COUNT(*) AS PATIENTS,
    ROUND(AVG(TOTAL_PAYMENT),2) AS AVG_COST
FROM MEDICARE_DATA
WHERE YEAR = target_year
GROUP BY DISEASE_COUNT
ORDER BY DISEASE_COUNT;


-- Mortality analysis

SELECT 
    CASE 
        WHEN DIABETES = 1 THEN 'DIABETES'
        ELSE 'NO_DIABETES'
    END AS DIABETES_STATUS,
    COUNT(*) AS PATIENTS,
    SUM(CASE WHEN DEATH_DATE IS NOT NULL THEN 1 ELSE 0 END) AS DEATHS,
    ROUND(SUM(CASE WHEN DEATH_DATE IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS MORTALITY_RATE
FROM MEDICARE_DATA
WHERE YEAR = target_year
GROUP BY DIABETES_STATUS;


-- Top high-cost patients

SELECT 
    BENEFICIARY_ID,
    YEAR,
    TOTAL_PAYMENT,
    STATE_CODE
FROM MEDICARE_DATA
WHERE YEAR = target_year
ORDER BY TOTAL_PAYMENT DESC
LIMIT 50;


-- ESRD cost impact

SELECT 
    ESRD_INDICATOR,
    COUNT(*) AS PATIENTS,
    ROUND(AVG(TOTAL_PAYMENT),2) AS AVG_COST,
    ROUND(MAX(TOTAL_PAYMENT),2) AS MAX_COST
FROM MEDICARE_DATA
WHERE YEAR = target_year
GROUP BY ESRD_INDICATOR;

END$$

DELIMITER ;